name: Smoke Tests (libc++)

on:
  workflow_dispatch:
  push:
    branches:
      - 'libc\+\+-build'

jobs:
  test-libcxx:
    strategy:
      fail-fast: true
      matrix:
        config:
          - {
              name: "host-x64-target-arm",
              prefix: "arm-none-eabi-",
              circle-machine: "1",
              qemu-bin: "qemu-system-arm",
              qemu-machine: "raspi0",
              qemu-kernel-opt: "-bios",
              qemu-img: "kernel.img",
            }
          - {
              name: "host-x64-target-aarch64",
              prefix: "aarch64-none-elf-",
              circle-machine: "3",
              qemu-bin: "qemu-system-aarch64",
              qemu-machine: "raspi3b",
              qemu-kernel-opt: "-kernel",
              qemu-img: "kernel8.img",
            }

    name: ${{ matrix.config.name }} - With libc++

    runs-on: docker

    container:
      image: codeberg.org/larchcone/ci/node-circle-stdlib:gcc15-v3

    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure circle-stdlib with QEMU support and libc++
        run: |
          ./configure -p ${{ matrix.config.prefix }} -r ${{ matrix.config.circle-machine }} --qemu --libcxx

      - name: Build libraries
        run: make -j$(nproc)

      - name: Build samples
        run: make build-samples

      - name: Run smoke test with QEMU
        run: |
          cd samples/05-smoketest
          ../../testdata/setup-sd.sh
          ulimit -t 300
          ${{ matrix.config.qemu-bin }} -M ${{ matrix.config.qemu-machine }} ${{ matrix.config.qemu-kernel-opt }} ${{ matrix.config.qemu-img }} -display none -nographic -semihosting -sd sdcard.img
